name: users_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  build: ^2.4.1
  auto_route: ^5.0.4
  bloc: ^8.0.3
  clock: ^1.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.0
  dartz: ^0.10.0-nullsafety.2
  device_info: ^2.0.0
  dio: ^5.2.1+1
  entry: ^0.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_libphonenumber: ^2.1.4
  flutter_platform_widgets: ^3.3.5
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  google_fonts: ^4.0.0
  google_sign_in: ^6.1.4
  implicitly_animated_reorderable_list: ^0.4.1
  intl: ^0.18.0
  flutter_i18n: ^0.33.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.0
  flutter_localizations: 
    sdk: flutter
  modal_bottom_sheet: ^3.0.0-pre
  package_info: ^2.0.0
  paginable: ^2.0.0
  provider: ^6.0.3
  sentry_flutter: ^7.8.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  mockito: ^5.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1 
  riverpod_generator: ^2.2.3
  auto_route_generator: ^5.0.3
  source_gen: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/i18n/locales/
  #  - test/i18n/locales/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
